# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Баклажан",
  "description": "Лучшие баклажаны на рынке"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные огурчики"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/2/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "products 7 and 3 ",
  "positions": [
    {
      "product": 3,
      "quantity": 30,
      "price": 30
    },
    {
      "product": 7,
      "quantity": 70,
      "price": 70
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/2/
Content-Type: application/json

{
  "positions": [
    {
      "product": 4,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?positions__product__id=5
Content-Type: application/json
